config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'search', to: 'search#show'

  resources :promotions do
    post 'generate_coupons', on: :member
    post 'approve',          on: :member
    get 'view_products', on: :member
    post 'add_products', on: :member
  end

  resources :coupons do
    post 'disable', on: :member, as: :disable
    post 'enable',  on: :member
  end

  namespace :admin do
    get 'admins', to: 'admins#index'
 end



  resources :product_categories

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show]

  namespace :api, constraints: ->(req) { req.format == :json } do
    namespace :v1 do
      resources :promotions, only: [:show, :index, :create, :update, :destroy], param: :name
      resources :product_categories, only: [:show, :index, :create, :update, :destroy], param: :code
      resources :coupons, only: [:show], param: :code do
        post 'burn', on: :member
      end
    end
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  has_many :promotion_categories, dependent: :restrict_with_error
  has_many :promotions, through: :promotion_categories

  validates :name, :code, presence: { message: 'não pode ficar em branco' }

  validates :code, uniqueness: { message: 'deve ser único' }

  def can_update?(params)
    params.key?(:name) &&
      params.key?(:code)
  end
end

app/controllers/api/v1/product_categories_controller.rb
class Api::V1::ProductCategoriesController < Api::V1::ApiController
  before_action :fecth_product_category, only: %i[show update destroy]

  def show
    @product = ProductCategory.find_by!(code: params[:code])
    render json: @product
  end

  def index
    @products = ProductCategory.all
    render json: @products unless @products.empty?
  end

  def create
    @product = ProductCategory.create!(product_category_params)
    render json: @product
  end

  def update
    raise ActiveRecord::RecordInvalid unless @product.can_update?(product_category_params)

    @product.update!(product_category_params)
    render json: @product
  end

  def destroy
    @product.destroy!
  end
end

private

def product_category_params
  params.require(:product_category).permit(:name, :code)
end

def fecth_product_category
  @product = ProductCategory.find_by!(code: params[:code])
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :fetch_product, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @products = ProductCategory.all
  end

  def show; end

  def new
    @product = ProductCategory.new
  end

  def create
    @product = ProductCategory.new(product_params)
    if @product.valid?
      @product.save
      redirect_to_show
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      flash[:notice] = t('.success')
      redirect_to_show
    else
      render :edit
    end
  end

  def destroy
    @product.delete
    flash[:notice] = t('.success', name: @product.name)
    redirect_to_index
  end

  private

  def product_params
    params.require(:product_category).permit(:name, :code)
  end

  def fetch_product
    @product = ProductCategory.find(params[:id])
  end

  def redirect_to_show
    redirect_to @product
  end

  def redirect_to_index
    redirect_to product_categories_path
  end
end

app/views/product_categories/_form_product_categories.html.erb
<div>
  <%= link_to t('buttons.back'), @product, class: 'btn' %>
</div><br>

<h2><%= header_title %></h2>

<% if @product.errors.any? %>
    <ul>
      <% @product.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
<% end %>

<%= form_with model: product do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <br>
  <div>
    <%= form.label :code%>
    <%= form.text_field :code %>
  </div>
  <br>
  <div><%= form.submit class: 'btn'%></div>
<% end %>

app/views/product_categories/edit.html.erb
<%= render partial: 'form_product_categories', locals:{
                                                      product: @product,
                                                      header_title: t('.header_title')
                                                      } %>

app/views/product_categories/index.html.erb
<h1><%= ProductCategory.model_name.human(count:2) %></h1>
<div>
  <%= link_to t('buttons.back'), root_path, class: 'btn' %>
  <%= link_to link_to t('buttons.register', model: @products.model.model_name.human), new_product_category_path, class: 'btn' %>
</div>

<div>
  <% if @products.empty?%>
    <h3><%= t('.empty') %></h3>
  <% else %>
    <h3><%=t('.active_products') %></h3>
  <% end %>
</div>
<dl>
  <% @products.each do |product| %>
    <dt><%=  link_to product.name, product, class: 'btn' %></dt>
  <% end %>
</dl>

app/views/product_categories/new.html.erb
<%= render partial: "form_product_categories", locals:{
                                                      product: @product,
                                                      header_title: t('.header_title')
                                                      } %>

app/views/product_categories/show.html.erb
<div>
  <%= link_to t('buttons.back'), product_categories_path, class: 'btn' %>
  <%= link_to t('buttons.edit', model: ProductCategory.model_name.human), edit_product_category_path(@product), class: 'btn' %>
  <%= link_to t('buttons.delete', model: ProductCategory.model_name.human), product_category_path(@product), method: :delete, class: 'btn' %>
</div>
<br>
<table class='table'>
  <thead>
    <tr>
      <th><%= ProductCategory.human_attribute_name(:name) %></th>
      <th><%= ProductCategory.human_attribute_name(:code) %></th>
    </tr>
  </thead>
  <tbody>
     <tr class='data'>
      <th><%= @product.name %></th>
      <th><%= @product.code %></th>
    </tr> 
  </tbody>
</table>