config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'search', to: 'search#show'

  resources :promotions do
    post 'generate_coupons', on: :member
    post 'approve',          on: :member
    get 'view_products', on: :member
    post 'add_products', on: :member
  end

  resources :coupons do
    post 'disable', on: :member, as: :disable
    post 'enable',  on: :member
  end

  namespace :admin do
    get 'admins', to: 'admins#index'
 end



  resources :product_categories

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show]

  namespace :api, constraints: ->(req) { req.format == :json } do
    namespace :v1 do
      resources :promotions, only: [:show, :index, :create, :update, :destroy], param: :name
      resources :product_categories, only: [:show, :index, :create, :update, :destroy], param: :code
      resources :coupons, only: [:show], param: :code do
        post 'burn', on: :member
      end
    end
  end
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  belongs_to :user
  has_many :coupons, dependent: :destroy # restrict_with_error
  has_one :promotion_approval, dependent: :destroy
  has_one :approver, through: :promotion_approval, source: :user
  has_many :promotion_categories, dependent: :destroy
  has_many :product_categories, through: :promotion_categories

  validates :name, :code, :discount_rate, :coupon_quantity, :expiration_date, presence: true

  validates :name, :code, uniqueness: true

  validate :expiration_date_cannot_be_in_the_past

  def generate_coupons!
    return if coupons?

    (1..coupon_quantity).each do |number|
      coupons.create!(code: "#{code}-#{format('%04d', number)}")
    end
  end

  def coupons?
    coupons.any?
  end

  def self.search(query)
    where('name LIKE ?', "%#{query}%") # .limit(5)
  end

  def approved?
    promotion_approval.present?
  end

  def self.approved
    joins(:promotion_approval)
  end

  def self.pending
    all - approved
  end

  def can_approve?(current_user)
    user != current_user
  end

  def can_delete?
    coupons.active.empty?
  end

  def can_update?(params)
    params.key?(:name) &&
      params.key?(:code) &&
      params.key?(:discount_rate) &&
      params.key?(:coupon_quantity) &&
      params.key?(:expiration_date)
  end

  def prod_exists?(prod)
    PromotionCategory.where(['promotion_id = ? and product_category_id = ?', id, prod.id]).empty?
  end

  private

  def expiration_date_cannot_be_in_the_past
    return unless expiration_date.present? && expiration_date < Date.current

    errors.add(:expiration_date, 'não pode ser no passado')
  end
end

app/controllers/api/v1/promotions_controller.rb
class Api::V1::PromotionsController < Api::V1::ApiController
  before_action :fetch_promotion, only: %i[show update destroy]

  def show
    render :show
  end

  def index
    @promotions = Promotion.all
    raise ActiveRecord::RecordNotFound unless @promotions.any?

    render json: @promotions
  end

  def create
    @promotion = Promotion.create!(promotion_params)
    render :show, status: :created
  end

  def update
    raise ActiveRecord::RecordInvalid unless @promotion.can_update?(promotion_params)

    @promotion.update!(promotion_params)
    render :show
  end

  def destroy
    raise ActiveRecord::RecordNotDestroyed unless @promotion.can_delete?

    @promotion.destroy!
    render json: "Promoção #{@promotion.name} apagada com sucesso", status: :no_content
  end
end

private

def fetch_promotion
  @promotion = Promotion.find_by!(name: params[:name])
end

def promotion_params
  params.require(:promotion).permit(:name,
                                    :description,
                                    :code,
                                    :discount_rate,
                                    :coupon_quantity,
                                    :expiration_date,
                                    :user_id)
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_promotion, only: %i[show edit update destroy generate_coupons approve]
  def index
    query = params[:query]
    if query == ''
      flash.now[:notice] = t('.show_all')
      @promotions = Promotion.all
    else
      @promotions = Promotion.search(query)
    end
  end

  def show; end

  def new
    # @cat == current_user.is_admin?
    @promotion = Promotion.new
  end

  def create
    # @promotion = Promotion.new(promotion_params)
    # @promotion.user = current_user  #outra opção
    # Promotion.new(**promotions_params, user: current_user) -> Double splat operator (merge de cjaves para hash)
    @promotion = current_user.promotions.new(promotion_params) # vem por causa do has_many
    if @promotion.save

      redirect_to_show
    else
      render :new
    end
  end

  def edit; end

  def update
    return unless @promotion.can_update?(promotion_params)

    if @promotion.update(promotion_params)
      flash[:notice] = t('.success')
      redirect_to_show
    else
      render :edit
    end
  end

  def generate_coupons
    @promotion.generate_coupons!
    flash[:notice] = t('.success')
    redirect_to_show
  end

  def destroy
    if @promotion.can_delete?
      @promotion.destroy
      flash[:notice] = t('.success', promotion_name: @promotion.name)
      redirect_to_index
    else
      flash[:notice] = t('.failed')
      redirect_to_show
    end
  end

  def approve
    if @promotion.can_approve?(current_user)
      current_user.promotion_approvals.create!(promotion: @promotion)
      PromotionMailer
        .with(promotion: @promotion, approver: current_user)
        .approval_email
        .deliver_now
      redirect_to @promotion, notice: t('.success')
    else
      redirect_to @promotion, notice: t('.failure')
    end
  end

  def view_products
    @prods = ProductCategory.all
    @promotion = Promotion.find(params[:id])
  end

  def add_products
    ids = params[:product_categories_ids].reject!(&:empty?)
    @promotion = Promotion.find(params[:id])
    ids.each do |id|
      @product_category = ProductCategory.find(id)
      flash[:notice] = 'já está nessa promoção' unless @promotion.prod_exists?(@product_category)

      PromotionCategory.create!(promotion: @promotion, product_category: @product_category)
    end
    redirect_to_show
  end

  private

  def promotion_params
    params.require(:promotion).permit(:name,
                                      :description,
                                      :code,
                                      :discount_rate,
                                      :coupon_quantity,
                                      :expiration_date)
  end

  def fetch_promotion
    @promotion = Promotion.find(params[:id])
  end

  def redirect_to_show
    redirect_to @promotion
  end

  def redirect_to_index
    redirect_to promotions_path
  end
end

app/views/promotions/_form_promotions.html.erb
<div>
  <%= link_to t('buttons.back'), promotions_path, class: 'btn' %>
</div>
<br>
<h2><%= header_title %></h2>

<% if promotion.errors.any?%>
  <ul>
    <% promotion.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: promotion do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <br>
  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
  <br>
  <div>
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>
  <br>
  <div>
    <%= form.label :discount_rate %>
    <%= form.number_field :discount_rate, in: 0..100 %>
  </div>
  <br>
  <div>
    <%= form.label :coupon_quantity %>
    <%= form.number_field :coupon_quantity, min:1 %>
  </div>
  <br>
  <div>
    <%= form.label :expiration_date %>
    <%= form.date_field :expiration_date %>
  </div>
  <br>
  <div><%= form.submit class: 'btn' %></div>
<% end %>

app/views/promotions/_promotion.html.erb
<em><ins><%= header_title %></ins></em>

<% promotions.each do |promotion| %>
  <p><%= link_to promotion.name, promotion, class: 'btn' %></p>
<% end %>

app/views/promotions/edit.html.erb
<%= render partial: 'form_promotions', locals:{
                                              promotion: @promotion, 
                                              header_title: t('.header_title')
                                              } %>

app/views/promotions/index.html.erb
<h1><%= Promotion.model_name.human(count:2)%></h1>
<div>
  <%= link_to t('buttons.back'), root_path , class: 'btn'%>
  <%= link_to t('buttons.register', model: Promotion.model_name.human), new_promotion_path, class: 'btn'%>
</div>
<div id="search">
  <%= form_with url: search_path, method: :get do |f| %>
    <br>
    <%= f.text_field :query, placeholder: t('.search_header'),  size:"30" , class: 'search'%>
    <%= f.submit t('buttons.search'), class: 'btn' %>
  <% end %>
</div>
<div>
  <% if Promotion.all.empty? %>
    <h3><p><%= t('.empty') %></p></h3>
  <% end %>

    <br>
    <% if @promotions.approved.any?%>
    <div id='approved'>
      <%= render partial: 'promotion', locals:{promotions: @promotions.approved, 
                                               header_title:t('headers.approved')}%>
    </div>
    <% end %>

    <% if @promotions.pending.any?%>
      <div id='pending'>
        <%= render partial: 'promotion', locals:{promotions: @promotions.pending, 
                                               header_title:t('headers.pending')} %>
      </div>
    <% end %>
</div>

app/views/promotions/new.html.erb
<%= render partial: 'form_promotions', locals:{
                                              promotion: @promotion,
                                              header_title: t('.header_title')
                                              } %>

app/views/promotions/show.html.erb
<div>
  <%= link_to t('buttons.back'), promotions_path, class: 'btn' %>

  <% if @promotion.coupons.active.empty? %>
    <%= link_to t('buttons.delete', model: Promotion.model_name.human), promotion_path(@promotion), method: :delete,class: 'btn'%>
  <% end%>

  <% if @promotion.coupons.empty?%>
    <%= link_to t('buttons.edit', model: Promotion.model_name.human), edit_promotion_path(@promotion), class:'btn' %>
  <% end %>
</div>

<h3><%= "#{@promotion.name} - #{@promotion.description}" %></h3>
<table id='promotion_table'>
  <thead>
    <tr>
      <th style='width: 70px'><%= Promotion.human_attribute_name(:code) %></th>
      <th style='width: 70px'><%= Promotion.human_attribute_name(:discount_rate) %></th>
      <th style='width: 70px'><%= Coupon.model_name.human(count:2)%> </th>
      <th style='width: 100px'><%= Promotion.human_attribute_name(:expiration_date) %></th>
    </tr>
  </thead>
  <tbody>
     <tr class='data'>
      <td><%= @promotion.code %></td>
      <td><%= number_to_percentage @promotion.discount_rate, precision:2 %></td>
      <td><%= @promotion.coupon_quantity %></td>
      <td><%= l(@promotion.expiration_date)%></td>   <%# I18n.localize => l %>
    </tr> 
  </tbody>
</table>
<br>
<% if @promotion.approved?%>
  <% if @promotion.coupons.empty?%>
      <%= link_to t('.generate_coupons'), generate_coupons_promotion_path(@promotion), method: :post, class: 'btn' %>  <%# I18n.translate => t%>
  <% else %>                                               <%# '.generate-coupons => lazy lookup, olhando dentro de promotions, dentro de show%>
    <h3><%= t('.active_coupons') %></h3>

    <table id='coupon_table'>
        <thead>
          <tr >
            <th style='width: 100px'><%= Coupon.human_attribute_name(:code) %></th>
            <th style='width: 100px'><%= Coupon.human_attribute_name(:status) %></th>
            <th style='width: 100px'><%= t('headers.action') %></th>
          </tr>
        </thead>
      <% @promotion.coupons.each do |coupon| %>
        <tbody>
          <tr class='data'>
            <td><%= coupon.code %></td>
            <td ><%= Coupon.human_attribute_name("status.#{coupon.status}")%></td>
            <td id="action-<%= coupon.code.parameterize%>">
              <% if coupon.active? %>
                <%= link_to t('.disable'), disable_coupon_path(coupon), method: :post,  class: 'btn' %>
              <% else %>
                <%= link_to t('.enable'), enable_coupon_path(coupon),method: :post, class:'btn' %>
              <% end %>
            </td>
          </tr> 
        </tbody>
      <% end %>
    </table>
  <% end %>
  <br>
<% else%>
  <%= link_to t('.approve'), approve_promotion_path(@promotion),method: :post, data: {confirm: t('.are_you_sure?')}, class: 'btn'%>
<% end %>
<div>
<p><%= t('headers.created_by') %>: <%= @promotion.user.email %></p>
<% if @promotion.approved?%>
  <p><%= t('headers.approved_by') %>: <%= @promotion.promotion_approval.user.email %></p>
<% end %>
</div>

<%= link_to 'Selecionar Produtos', view_products_promotion_path(@promotion), class: 'btn' %>


<% @promotion.product_categories.each do |pc| %>
  <%= pc.code %>
<% end %>

app/views/promotions/view_products.html.erb
<%= form_with url: add_products_promotion_path do |form| %>
  <div>
		<%= form.collection_check_boxes :product_categories_ids, @prods, :id, :code %>
	</div>
  <br>
  <br>
  <div><%= form.submit class: 'btn' %></div>
<% end %>