config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'search', to: 'search#show'

  resources :promotions do
    post 'generate_coupons', on: :member
    post 'approve',          on: :member
    get 'view_products', on: :member
    post 'add_products', on: :member
  end

  resources :coupons do
    post 'disable', on: :member, as: :disable
    post 'enable',  on: :member
  end

  namespace :admin do
    get 'admins', to: 'admins#index'
 end



  resources :product_categories

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show]

  namespace :api, constraints: ->(req) { req.format == :json } do
    namespace :v1 do
      resources :promotions, only: [:show, :index, :create, :update, :destroy], param: :name
      resources :product_categories, only: [:show, :index, :create, :update, :destroy], param: :code
      resources :coupons, only: [:show], param: :code do
        post 'burn', on: :member
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('headers.app_name') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = 'body'>
    <nav class='nav-menu'>
      <%  if user_signed_in? %>
          <ul>
            <li> <%= link_to 'Home', root_path, class: 'btn_nav' %></li>
            <li><%= link_to  Promotion.model_name.human(count:2), promotions_path, class: 'btn_nav'%></li>
            <li><%= link_to  ProductCategory.model_name.human(count:2), product_categories_path, class: 'btn_nav'%></li>
            <li><%= link_to t('buttons.logout'),  destroy_user_session_path, method: :delete, class: 'btn_nav'%></li>
          </ul>
          <ul class = user>
            <li><%= link_to current_user.email, user_path(current_user), class: 'btn_nav user' %></li>
          </ul> 
       <% else %>
          <ul>
            <li><%= link_to t('buttons.register_user'), new_user_registration_path,class: 'btn_nav' %></li>
            <li><%= link_to t('buttons.login'), new_user_session_path,class: 'btn_nav'%></li>
          </ul>
      <% end %>
    </nav>
    <em id='flash' class ='flash'><%= flash[:notice] %></em>
    <div class='pag'>
     <%= yield %>
    </div>
  </body>
</html>